"""Shared domain contracts. Agent A owns this package."""

from app.domain.aggregation import ThermalAggregationSpec, default_thermal_aggregation_spec
from app.domain.enums import (
    AnalysisMode,
    DataMode,
    DataStatus,
    HeatmapTemporalMode,
    JobStatus,
    ReferenceFrame,
    ResultStatus,
    SystemLimitationCode,
    ThermalDataSource,
    ThermalStatistic,
    TileAssignmentMethod,
    UpstreamTimeSemantics,
    ZoneAggregationStatistic,
)
from app.domain.evidence import EvidenceEdge, EvidenceGraph, EvidenceNode
from app.domain.features import ZoneFeatureVector
from app.domain.gate0 import (
    Gate0Capability,
    Gate0CapabilityStatus,
    Gate0Decision,
    Gate0DecisionStatus,
    Gate0HumanCloseApproval,
    Gate0Ledger,
    Gate0OverallStatus,
)
from app.domain.interventions import InterventionDefinition
from app.domain.normalization import NormalizedFeature
from app.domain.phoenix_v1 import (
    DECISION8_POLICY_VERSION,
    REFERENCE_VERSION,
    ZONE_GEOMETRY_VERSION,
    decision8_policy_fixture,
)
from app.domain.policies import (
    ConfidencePolicy,
    CoveragePolicy,
    HazardSpreadPolicy,
    HistoricalReferenceSpec,
    ModuleFlags,
)
from app.domain.requests import AnalysisRequest, ScenarioRequest
from app.domain.results import (
    AnalysisResult,
    Confidence,
    EngineResult,
    HazardSpreadProvenance,
    PortfolioRecommendation,
    ZoneDecisionResult,
)
from app.domain.job_lifecycle import (
    CostAuthorization,
    CostAuthorizationState,
    ExecutionState,
    JobTerminality,
    SignalPhase,
    SignalProgress,
    SignalSection,
    SignalSectionError,
    TwoSignalJobState,
    derive_job_terminality,
    effective_section_availability,
)
from app.domain.signals import (
    HistoricalNormalizedSignalState,
    SelectedTimeSnapshot,
    SelectedTimeSnapshotZone,
    SignalAvailability,
    SignalProvenance,
    ThermalSignalKind,
    TwoSignalAssembly,
    TwoSignalAvailability,
)
from app.domain.thermal import ThermalObservation, ZoneThermalSeries
from app.domain.versions import AnalysisVersions
from app.domain.zones import AnalysisZone, GeoJSONGeometry, UpstreamPartition

__all__ = [
    "AnalysisMode",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisVersions",
    "AnalysisZone",
    "Confidence",
    "ConfidencePolicy",
    "CostAuthorization",
    "CostAuthorizationState",
    "ExecutionState",
    "JobTerminality",
    "SignalPhase",
    "SignalProgress",
    "SignalSection",
    "SignalSectionError",
    "TwoSignalJobState",
    "derive_job_terminality",
    "effective_section_availability",
    "CoveragePolicy",
    "DataMode",
    "DataStatus",
    "EngineResult",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceNode",
    "GeoJSONGeometry",
    "Gate0Capability",
    "Gate0CapabilityStatus",
    "Gate0Decision",
    "Gate0DecisionStatus",
    "Gate0HumanCloseApproval",
    "Gate0Ledger",
    "Gate0OverallStatus",
    "HazardSpreadPolicy",
    "HazardSpreadProvenance",
    "HeatmapTemporalMode",
    "HistoricalNormalizedSignalState",
    "HistoricalReferenceSpec",
    "InterventionDefinition",
    "JobStatus",
    "ModuleFlags",
    "NormalizedFeature",
    "PortfolioRecommendation",
    "ReferenceFrame",
    "ResultStatus",
    "ScenarioRequest",
    "SelectedTimeSnapshot",
    "SelectedTimeSnapshotZone",
    "SignalAvailability",
    "SignalProvenance",
    "SystemLimitationCode",
    "ThermalAggregationSpec",
    "ThermalDataSource",
    "ThermalSignalKind",
    "ThermalObservation",
    "ThermalStatistic",
    "TileAssignmentMethod",
    "TwoSignalAssembly",
    "TwoSignalAvailability",
    "UpstreamPartition",
    "UpstreamTimeSemantics",
    "ZoneAggregationStatistic",
    "ZoneDecisionResult",
    "ZoneFeatureVector",
    "ZoneThermalSeries",
    "default_thermal_aggregation_spec",
]
